# Generated by Django 4.0.3 on 2022-03-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contributor_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
    ]
