# Generated by Django 4.0.3 on 2022-03-23 14:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contributor_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('user'), django.db.models.expressions.F('project'), name='One contributor per project'),
        ),
    ]
