# Generated by Django 4.0.3 on 2022-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contributor_one contributor per project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contributor',
            name='One contributor per project',
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='One contributor per project'),
        ),
    ]
