# Generated by Django 4.0.3 on 2022-03-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_contributor_one contributor per project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contributor',
            name='One contributor per project',
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user', 'project')},
        ),
    ]
